name: Build for macOS

on:
  workflow_dispatch:

jobs:
  mac_build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: cmake
      shell: bash
      run: |
        cd /Users/runner/work/FMC-backend-plugin/FMC-backend-plugin/
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER="g++-14" -DCMAKE_C_COMPILER="gcc-14"
        make
        
    - name: Save files
      uses: actions/upload-artifact@v4
      with:
        name: Output
        path: /Users/runner/work/FMC-backend-plugin/FMC-backend-plugin/777_systems/
